server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/machine_checklist
    username: postgres
    password: 12345678
    hikari:
      maximum-pool-size: 40
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB
      enabled: true
  quartz:
    job-store-type: jdbc # เปลี่ยนเป็น jdbc ใน production
    jdbc:
      initialize-schema: always
    properties:
      org:
        quartz:
          scheduler:
            instanceName: ChecklistScheduler
            instanceId: AUTO

jwt:
  secret: PP/e22h/W97Ahtx26r/fGTAnQQgvwvN7OPyP5Kp7NT0bnYvwSUJZ/DSwG183hkLH
  secrete-exp: 864000000
  secrete-exp-min: 60
logging:
  level:
    root: INFO
    com.example.demo: DEBUG
    org.springframework: INFO
    org.quartz: INFO